apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-backend-app
spec:
  selector:
    matchLabels:
      app: post-backend-app
  replicas: 3
  template:
    metadata:
      labels:
        app: post-backend-app
    spec:
      containers:
        - name: post-backend-app
          image: domzem/post-backend:1.0
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: 'postgres://user:secret@post-db-service:5432/post?schema=public'
            - name: FRONTEND_URL
              value: 'http://post-frontend-service:8080'
---
apiVersion: v1
kind: Service
metadata:
  name: post-backend-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: post-backend-app
  type: LoadBalancer
