apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db
spec:
  selector:
    matchLabels:
      app: post-db
  replicas: 1
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
        - name: post-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: 'user'
            - name: POSTGRES_PASSWORD
              value: 'secret'
            - name: POSTGRES_DB
              value: 'post'
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: post-db-service
spec:
  selector:
    app: post-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
