services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'post'
    ports:
      - '5432:5432'
    networks:
      - post-network
  nest-backend:
    build: ./nest-backend
    container_name: nest-backend
    environment:
      DATABASE_URL: 'postgresql://user:secret@postgres-db:5432/post?schema=public'
    ports:
      - '3000:3000'
    networks:
      - post-network
    depends_on:
      - postgres-db

networks:
  post-network:
