apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-frontend-app
spec:
  selector:
    matchLabels:
      app: post-frontend-app
  replicas: 3
  template:
    metadata:
      labels:
        app: post-frontend-app
    spec:
      containers:
        - name: post-frontend-app
          image: domzem/post-frontend:1.0
          ports:
            - containerPort: 8080
          env:
            - name: NEXT_PUBLIC_BACKEND_API_URL
              value: 'http://post-backend-service:3000' # Not working
            - name: BACKEND_API_URL
              value: 'http://post-backend-service:3000'
---
apiVersion: v1
kind: Service
metadata:
  name: post-frontend-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: post-frontend-app
  type: LoadBalancer
