name: Deploy Frontend App
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Install frontend dependencies
        run: |
          cd next-frontend
          npm ci
      - name: Test frontend code
        run: |
          cd next-frontend
          npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Install frontend dependencies
        run: |
          cd next-frontend
          npm ci
      - name: Build frontend app
        run: |
          cd next-frontend
          npm run build
      - name: Deploy frontend app
        run: echo "Deploying code to production"
